### PR TITLE
Style: migration to twitter bootstrap 3

### PR DESCRIPTION
**Pull request by kneczaj**
- fast replacement - accordion, accordion-toggle deleted
- header porting completed
- searchbar migration
- fixed different padding at different window widths
- css fom page.html, header.html moved to base.css
- layout of the search page adapted
- footer stylization
- portalboxes migrated to panels
- registration, login page form migration
- icon -> glyphicon replacement
- account management page migrated
- navarheader substituted with dropdown-header in a couple of places
- search settings menu improved
- advanced search form adapted
- replaced all occurences of buttons-radio -> buttons
- searchbar and search options menu improvements
- search settings layout improved
- migration to bootstrap-typeahead
- makefile modified to install bootstrap3 and bootstrap-typeahead
- deposit form
- messages menu
- new message form
- autocompletition in deposit form
- write comment modal + add review modal
- Add To Search form converted from dropdown to collapsable

### CODE REVIEW

**Comment by jirikuncar** [comment]
Please, could you rebase to latest `pu` branch? We can’t automatically merge this pull request.

**Comment by kneczaj** [comment]
rebased

**Comment by jirikuncar** [comment]
There is a failed test see: https://travis-ci.org/jirikuncar/invenio/jobs/14914813

**Comment by kneczaj** [comment]
I guess that this is sth related to translation, but i have no idea what
exactly is going on. I didn't touch the placeholders (translations?) and
the ones which the error concerns seems to exist in the code many times.

When it comes to other comments, which I received at my mailbox, I don't
see them at github - I see just yours that I should rebase. I look at this
link which is on bottom of the emails from github
https://github.com/kneczaj/invenio/commit/4d280ea0618bbb22076a3c078c2ea91097ed549b#commitcomment-4765288Any
idea why?

**Comment by adrianp** [comment]
@kneczaj When you force push after a rebase the comments on the current request disappear as they make no sense in the new version (they are linked to code lines which might change). You have 2 options:
- Instead of rebasing, you `fetch` & `merge` (or `pull`).
- **You account for all comments before force pushing a rebased branch.**

**Comment by lnielsen** [comment]
Tests are still failing, so I can't merge yet.

**Comment by kneczaj** [comment]
I work on different branch right now, will pull it when I finish the
typeahead. This one test, which Jiri noticed doesn't pass, is repaired.

2013/12/12 Lars Holm Nielsen notifications@github.com

**Pull request closed without merging**
