### PR TITLE
PLEASE REVIEW: jsonalchemy: JSON search addition

### PR DESCRIPTION
**Pull request by adrianp**
Signed-off-by: Adrian-Tudor Panescu adrian.tudor.panescu@cern.ch

### CODE REVIEW

**Comment by egabancho** [comment]
will  `def search(self, query)` be easily portable to postgresql?

**Comment by adrianp** [comment]
Tested now on psql 9.3.2 and you can do something like:

``` sql
SELECT * FROM some_table WHERE json->'foo'->>'bar' = 'baz';
```

and all rows where the `json` field looks like:

``` json
{"foo": {"bar": "baz"}}
```

will be selected.

It seems like SQLAlchemy does not currently support this (or at least I couldn't find it), but I guess it will be quite easy to use a Python dictionary given psql's syntax.

**Comment by egabancho** [comment]
I couldn't find anything neither when I was looking some time ago.

Indeed it looks easy to transform a dictionary into psql's syntax

**Comment by jirikuncar** [comment]
@egabancho it is ok to merge it?

**Comment by egabancho** [comment]
Yeap!

**Pull request merged**
