### PR TITLE
Commit try a

### PR DESCRIPTION
**Pull request by PXke**
A new try for merge :D 

Add everything for the new harvesting with workflows !

### CODE REVIEW

**Comment by egabancho** [comment]
Only one little thing!
I'm almost 100% sure that you are doing it but just in case ;-)
If the modifications that you are doing in the legacy modules are 'welcome' in the master branch maybe you want to provide a path for them :-)

**Comment by jirikuncar** [comment]
Sorry, a test is failing. Please fix it.

**Comment by PXke** [comment]
@jirikuncar  It is my bad :dancers: . It should be working now ! I forgot that I did a modification far in the past about the celery test. Sorry.

@egabancho : Haha hopefully you warn me because I didn't think to this at all ! In fact I don't know if it is welcome or not  :interrobang: but because we are using a lot of technologies from the next branch I think it will not be.  I will take contact !

**Comment by jirikuncar** [comment]
It looks ok. Shall I merge it?

**Comment by PXke** [comment]
if you can, Yes please !

**Comment by lnielsen** [comment]
What is the reason for changing serialization from msgpack to pickle?

**Comment by PXke** [comment]
Hello ! :) 
So the explanation will perhaps not convince you at 100%, but unfortunately we sometimes have  to send to celery some complex objects.

For example we are encapsulating id of workflow object into object to be able to retrieve them into Celery. ( To avoid a problem of mapping with SQLalchemy) 

There was also another moment, we were directly sending workflow objects. 

The problem is that not everything is (Jsonifyable  ? ) easily. Msgpack was crashing by trying to send this type of things. One solution would have been to pre-create a dictionary and serialize everything which could cause trouble. And then send this dictionary and processed it again at the other side of the river.

The other solution was the pickle things.  Except that it is far easier to do, at least it seems to be ! 

So we are using pickle to be able to send everything imaginable to celery ! 

I hope I have answered to your question :)

If you want us to change of solution don't hesitate ;) !

**Comment by lnielsen** [comment]
I think while the pickle solution is painless right now, I think it will likely cause problems downstream for a couple of reasons:

1) Imagine you have to stop the celery queue, while you still have tasks in it, then you upgrade your celery workers and start the queue again. If the object you have in the queue, doesn't match the code on in the worker you're in trouble.

2) You assume all workers are Python only workers, which might not always be convenient. Imagine e.g. video-encoding, Word doc transformation or something else, where it might be advantages to have a worker running in a different language.

I think it's better to leave it with msgpack (which is also a super-fast serializer), and then on a per-task basis change the serializer: http://docs.celeryproject.org/en/latest/userguide/calling.html#serializers

```
# instead of:
add.delay(10, 10)
# use:
add.apply_async((10, 10), serializer='pickle')
```

This allows you to use pickle only when really needed.

**Comment by PXke** [comment]
Okay well received ;) 

We will find a way to make it work with message !

**Pull request merged**
